# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "infernix/tinycore"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", inline: "echo Hello, World", privileged: false
end
