Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
  end
end

include_vagrantfile = File.expand_path("../_Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
