name: docker-image-test

on:
  pull_request:


permissions:
  packages: write
  pull-requests: write

jobs:
  generate-docker-metadata:
    uses: vagrant-libvirt/vagrant-libvirt/.github/workflows/docker-meta.yml@fix-docker-image-publish
    secrets: inherit

  generate-docker-metadata-slim:
    uses: vagrant-libvirt/vagrant-libvirt/.github/workflows/docker-meta.yml@fix-docker-image-publish
    with:
      flavor: |
        suffix=-slim
    secrets: inherit

  build-docker-image:
    runs-on: ubuntu-22.04
    needs:
      - generate-docker-metadata
      - generate-docker-metadata-slim
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Build and push main image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ needs.generate-docker-metadata.outputs.tags }}
          target: final
          labels: ${{ needs.generate-docker-metadata.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
