name: publish-gem

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  packages: write

jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install rake & ruby
      run: |
        sudo apt-get install -y \
          rake \
          ruby \
          ;
    - name: Build gem
      run: |
        rake build
    - uses: actions/upload-artifact@v3
      with:
        name: gem
        path: pkg/**.gem

  publish-package:
    needs: build-package
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: gem
    - name: setup credentials
      run: |
        mkdir ~/.gem
        cat <<EOF > ~/.gem/credentials
        ---
        :github: Bearer ${GITHUB_TOKEN}
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: publish package
      run: |
        ls -la pkg/*.gem 
        echo "gem push --key github \
          --host https://rubygems.pkg.github.com/${GITHUB_REPOSITORY_OWNER} \
          pkg/*.gem"

